[plugin]
repository = "https://github.com/Infiziert90/TrackyTrack.git"
commit = "639a8a4a297d38d13c45ac5b5e419d234c77b35c"
owners = [
    "Infiziert90",
]
project_path = "TrackyTrack"
changelog = """
First Release~

Simple and Easy Data Tracking

+ Tracks data for Desynthesis
+ Tracks data for Venture Coffers (requires AllaganTools)
+ Tracks data for Gacha Coffers (requires AllaganTools)
+ Supports multiple characters

![desynthesis](https://raw.githubusercontent.com/Infiziert90/TrackyTrack/master/TrackyTrack/images/desynthesis.png)
![venture](https://raw.githubusercontent.com/Infiziert90/TrackyTrack/master/TrackyTrack/images/venturecoffer.png)
"""
