[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "158575f7d05595648b75267e06244bc466aa7447"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Builder]
+ Implemented build solver (thanks WildWolf)
+ Added breakpoint support for solver
+ Added border to build table
"""
