[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "d309fb0da61bb87516c755c9e379638d7f076f2a"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
+ Add newly found unlock paths
"""
