[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "ad0e3931564ddde1947a96ba27c2b5042785c38e"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
nofranz
"""
