[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "cb1fd6a18db6c09e97e03e27b704691d18a66d93"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Loot Tracking]
+ Cleanup old corrupted data before migrating
"""
