[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "16f296ac2eaa188b0fa157a4ddea4fb901f84060"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Builder]
+ Implemented save and load functionality

[Config]
+ Added new tab for saved builds
"""
