[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "1d1b484e4e36d0bf92841e81cb9007226947f266"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Info]
This update changes the internal loot tracking significantly and
old loot data is now marked as legacy.

[Changes]
+ Loot tracking update
+ Internal improvements
+ Voyage history includes more information now, like procs

[Important]
All config files must be migrated to the new version, and 
this is only possible while 1 client is running.

**DO NOT UPDATE WHILE YOU HAVE MULTIPLE CLIENTS RUNNING**
or your config and stored data is lost forever.
"""
