[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "8f5807eab09cee4beb77ce27220e873199369fa3"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Overlay]
+ Adjusted colors, also added a color to signal partly done
+ Fixed clipping with scrollbar
+ Added hovering tooltip for yellow submarine text

[Builder]
+ Added total exp to stats
+ Experimental option to allow specific sectors in the leveling module

[Loot]
+ Analyse Tab (WiP)

[Config > About]
+ Added Ko-Fi Link
"""
