[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "c25c0c478cb46a9b898620971372900c1cb5222f"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
+ Implement time frames for /sloot
+ Implement multi selection for loot table 
"""
