[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "311815447caf072633edb7b2b989d3a79b2c5127"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Loot Tracking]
+ Fix bug that prevented loot from being tracked
"""
