[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "5a57fee20a60b70f6667f1f426c6c95b39875b82"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Misc]
+ Improved UI for higher font scaling

[Tracker]
+ Added durability prediction

[Config]
+ Added option to show prediction (on by default)
"""
