[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "4cbd3a4e49861d8593987c05070b718a9a6daa9f"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Loot]
+ Added export functionality, exporting all the valid loot data into a csv for excel/spreadsheet

[Misc]
+ Added all breakpoints for the new sectors
"""
