[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "906d15371c83e6c548fec85f481e03e05812280c"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Overlay]
+ Adjusted colors, also added a color to signal partly done
+ Fixed clipping with scrollbar
+ Added hovering tooltip for yellow submarine text

[Builder]
+ Added total exp to stats
+ Experimental option to allow specific sectors in the leveling module
"""
