[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "7701c41b7f7cabb3649585399934e1af54c69205"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
nofranz
"""
