[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "fb8e0e3974afd6e3a00d615f8249901df335665c"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[New]
+ Added an option to allow freely resizing the FC button slider
"""
