[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "bb484d29be163ee6ebbc895f770eae130bce5b2c"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Helpy + Tracker]
+ Added storage tracking, requires AllaganTools to work

[storage](https://raw.githubusercontent.com/Infiziert90/SubmarineTracker/master/SubmarineTracker/images/storage.png)
"""
