[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "3b8f00ba66d39c0a65a773b6ac8a0abf008e76d2"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Tracker]
+ Added option to show route in All tab again
"""
