[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "500159635814e6d4b7ecfae2931a3234559bf573"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Overlay] (/soverlay)
New

[Notification Overlay]
Fully Removed

[Misc]
+ Automatic reload of changed configs
+ Plugin will keep 5 backups of each stored FC
"""
