[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "2357fe85fd783875543b4ce9ce6c3c03195ab471"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Tracker]
+ Prevent rare crash when building a new sub

[Builder]
+ Added fuel costs to stats (also shows your current stock if allagantools is installed)
+ Fix caching issue for Best EXP and Leveling calculator, if you used different characters in succession

[Helpy]
+ Prevent overscaling of the boxes if you used higher UI scaling than default dalamud
"""
