[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "0282d2a87c17a637a2997ad303bd605a6fb0391d"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Config]
+ New options got added
+ FC order can now be changed

[Tracker]
+ Added an 'All' button (enabled by default)

[Builder]
+ Added duration limits to best exp (24, 36 and 48h)
+ Added 'Must Include'

[Misc]
+ 6.4 support
"""
