[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "af5dd54b63be26bf5dcf4e68c4369266424dc3bf"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Builder]
+ Implemented build solver (thanks WildWolf)
+ Added breakpoint support for solver
+ Added border to build table
"""
