[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "a6e16afbdf1df5938cbd20d0280b5ae8b2bb48d6"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Config]
+ New options got added
+ FC order can now be changed

[Tracker]
+ Added an 'All' button (enabled by default)

[Builder]
+ Added duration limits to best exp (24, 36 and 48h)
"""
