[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "57d128c8f3ade4a17a590d2958deda9f729f0951"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Config]
+ New options got added
+ FC order can now be changed

[Tracker]
+ Added an 'All' button (enabled by default)

[Builder]
+ Added duration limits to best exp (24, 36 and 48h)
+ Added 'Must Include'

[Misc]
+ 6.4 support
"""
