[plugin]
repository = "https://github.com/Infiziert90/BlueMageHelper.git"
commit = "bad9a13223206b4ee4f8d95f2743ce5c41bf8847"
owners = [
    "Infiziert90",
]
project_path = "BlueMageHelper"
changelog = """
+ Added marker to show if a spell is learned
+ Added option to only show unlearned spells in spellbook
"""
