[plugin]
repository = "https://github.com/Infiziert90/DeathRoll.git"
commit = "9f8093bb66ffdaba9f030c5b85ec8a761f956e58"
owners = [
    "Infiziert90",
]
project_path = "DeathRoll"
changelog = """
Blackjack Mode:
+ Fix bug that prevents players from rolling
+ Only show table when needed
"""
