[plugin]
repository = "https://github.com/Infiziert90/ReadyCheckHelper.git"
commit = "d20afec0c68b8f00fdb26e89597135ba88fbaa4d"
owners = [
    "Infiziert90",
    "PunishedPineapple",
]
project_path = "ReadyCheckHelper"
