[plugin]
repository = "https://github.com/PunishedPineapple/ReadyCheckHelper.git"
commit = "ad25529ded9f9fb53549e2dfc3f872a2b2ae9436"
owners = [
    "Infiziert90",
    "PunishedPineapple",
]
project_path = "ReadyCheckHelper"
changelog = """
+ Added support for the new 'Align List to Bottom' option
"""
