[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "5f5c4bd348d45cf73e00f1a3340cf2bf9950e92c"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added /elbunny command
- Circle color can now be adjusted
- Added more tooltips
- Added more Pyros locations
- Only show closest location
"""
