[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "ae072ef3d4bd68d0fac3a502e862f26fe761ecc3"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
