[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "2731bc4df9bdd688da6e60cecfbd62a7f9327166"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added time to stats
- Added localization (wip)
- Fixed bug preventing stats counting in rare case
"""
