[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "8c5d518ef1f72cbbec8a57ab5ed0d1a0091920a2"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added 'Fairy Finder', this will notify you about nearby fairies/elementals
- Added 'Bunny Window', this will show you estimated respawn times (min and max)

- Added a shout delay of 20s, you can't use the shout option until this delay is over

- Randomization can be turned off
- Randomization is done in a 0.5 radius

- Added color to chat messages
- Slight UI improvements

- Removed TrackerFinder as it resulted in mostly false positives

Eureka Linker is the new display name and Infi took over the development.
The plugin will continue to exist as a lightweight alternative to EurekaHelper.

For suggestions or issues, please visit XIVLauncher & Dalamud Discord #plugin-help-forum
"""
