[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "72c977ae6b64efb21a198838d07b32d6dae029ef"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added 'Time in Eureka' to the stats
- Added localization (DE full, FR small parts, JA missing)
- Fixed a bug that prevented stats from counting correctly in rare case
- All fates coords are now perfectly centered (without randomize)
- Added more chests to low level pyros and pagos
"""
