[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "cfc79d271c3bc59ee3ec0c9fcdbd510537f685d9"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added 'Fairy Finder', this will notify you about close by fairies
- Added a shout delay of 30s, you can't use shout option until this delay is over

- Randomization is now done in a 0,5 radius
- Randomization can be turned off

- Chat messages are now colored
- Slight UI improvements

Eureka Linker is the new display name and Infi took over the development.
The plugin will continue to exist as a lightweight alternative to EurekaHelper.

For suggestions or issues, please visit XIVLauncher & Dalamud Discord #plugin-help-forum
"""
