[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "157faa7938af296cb006820f151a3fceac723470"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added /elbunny command
- Circle color can now be adjusted
- Added more tooltips
- Added more Pyros locations
"""
