[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "2309ff14d67e0b9741b7948eca44969e84aa6d06"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added 'Time in Eureka' to the stats
- Added localization (DE full, FR small parts, JA missing)
- Fixed a bug that prevented stats from counting correctly in rare case
- All fates coords are now perfectly centered (without randomize)
- Added more chests to Hydatos, low level pyros and pagos
"""
