[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "51ae2e23bf9032adae3f8183e5bae9971f579b54"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added time to stats
- Added localization (wip)
- Fixed bug preventing stats counting in rare case
"""
