[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "2271eb01d2d8239570563bf013909f6d9983334c"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
[Hotfix]
- Don't crash if user inputs old instance ID format
"""
