[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "10e88d6075953e6d2f2a3bff31f1ec1ccf43d81b"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
nofranz
"""
