[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "a5d07134580fcda9dd4055bef1c4f540707f6177"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added /elbunny command
- Circle color can now be adjusted
- Added more tooltips
- Added more Pyros locations
- Added more Pagos locations
- Only show closest location
- Added a small About tab

If you encounter any issues or have feedback, please use the plugin-forums thread in the XIVLauncher & Dalamud discord :)
"""
