[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "b08cb08169bc10a6ddce345caadfe6a45771a91a"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
[Hotfix]
- All commands act as toggles now
- More chests
"""
