[plugin]
repository = "https://github.com/Infiziert90/EurekaTrackerAutoPopper.git"
commit = "18066ce80ae5275fbde0542708b51e610b043cc0"
owners = [
    "Infiziert90",
    "electr0sheep",
]
project_path = "EurekaTrackerAutoPopper"
changelog = """
- Added time to stats
- Added localization (wip)
- Fixed bug preventing stats counting in rare case
- All fates coords should now be centered (without randomize)
"""
