[plugin]
repository = "https://github.com/Infiziert90/BetterPlaytime.git"
commit = "f273e67bced93419a4a95e5539d5a657bc7b590c"
owners = [
    "Infiziert90",
]
project_path = "BetterPlaytime"
changelog = """
+ Simple server bar integration
"""
