[plugin]
repository = "https://github.com/Infiziert90/BetterPlaytime.git"
commit = "8a53b45a1447b24807ff661356ff9f297ce2d271"
owners = [
    "Infiziert90",
]
project_path = "BetterPlaytime"
changelog = """
+ Add basic localization
+ Don't fail on specific exception for server bar
"""
