[plugin]
repository = "https://github.com/Infiziert90/Hunty.git"
commit = "daa7443b29b92b1bdd3bae9f329e7b8f09d42989"
owners = [
    "Infiziert90",
]
project_path = "Hunty"
changelog = """
nofranz
"""
