[plugin]
repository = "https://github.com/Infiziert90/Hunty.git"
commit = "b7b1dbd4edbe3f116e09bde7d6968cee7aa29603"
owners = [
    "Infiziert90",
]
project_path = "Hunty"
changelog = """
nofranz
"""
