[plugin]
repository = "https://github.com/imaginary-png/Fungah-Totally-Safe-Spot.git"
commit = "d71c735f1906b2bd3de080fc1df4161fa96d7826"
owners = [
    "imaginary-png",
]
project_path = "Fungah"
changelog = ""
