[plugin]
repository = "https://github.com/imaginary-png/Fungah-Totally-Safe-Spot.git"
commit = "e03be43cf6425a86c3edb227d6702f3c8c8aa999"
owners = [
    "imaginary-png",
]
project_path = "Fungah Safe Spot (sorta)"
changelog = ""