[plugin]
repository = "https://github.com/Infiziert90/Hunty.git"
commit = "cb06c8179762647f12df18cbcda3589139320664"
owners = [
    "Infiziert90",
]
project_path = "Hunty"
changelog = """
+ Automatically switch to the correct tab on job switch
+ Adjust some flags with incorrect locations
"""
