[plugin]
repository = "https://github.com/Infiziert90/Hunty.git"
commit = "961395c5ed4f7e75849dd0307c6d5eb02f55fa7f"
owners = [
    "Infiziert90",
]
project_path = "Hunty"
changelog = """
+ Check for job change
+ Fix Tree Slug position
"""
