[plugin]
repository = "https://github.com/Infiziert90/Hunty.git"
commit = "98a9c0019176dc3f361f3ba925030b2beab0ce9d"
owners = [
    "Infiziert90",
]
project_path = "Hunty"
changelog = """
+ Automatically switch to the correct tab on job switch
+ Adjust some flags with incorrect locations
"""
