[plugin]
repository = "https://github.com/Infiziert90/Hunty.git"
commit = "6bc18cf174e9d62a7756f2dff1134acf6916424b"
owners = [
    "Infiziert90",
]
project_path = "Hunty"
changelog = """
+ Check for job change
"""
