[plugin]
repository = "https://github.com/Infiziert90/Hunty.git"
commit = "297216f81bded5b24b983d5782477ef999e98d68"
owners = [
    "Infiziert90",
]
project_path = "Hunty"
changelog = """
+ Automatically switch to the correct tab on job switch
+ Adjust some flags with incorrect locations
"""
