[plugin]
repository = "https://github.com/Infiziert90/Hunty.git"
commit = "b321fdaeef88e7bbc88413c04afaca07e60e98e3"
owners = [
    "Infiziert90",
]
project_path = "Hunty"
changelog = """
+ Add hunty to testing
"""
