[plugin]
repository = "https://github.com/shdwp/xivFaderPlugin.git"
commit = "cc20c4dfba5039d7ee3901b8c0870ab8801fe505"
owners = ["shdwp", "Aelexe", "Infiziert90"]
project_path = "FaderPlugin"
changelog = """
Release v2.3.4.0
- Prevent hasIdled from looping
- More UI improvements
- Add 2 new commands, on and off
- Add a warning for cross hotbars
  + Cross hotbars with 'Always display WXHVB' will not go invisible unless the option 'Position WXHB separately from XHB' is also used
"""
