[plugin]
repository = "https://github.com/shdwp/xivFaderPlugin.git"
commit = "96bf2d625ec95951c41119a7b71fbb1017cb4b81"
owners = ["shdwp", "Aelexe", "Infiziert90"]
project_path = "FaderPlugin"
changelog = """
Release v2.3.4.0
- Add WeaponUnsheathed state
- Add Island Sanctuary state 
- Duty state doesn't apply to island sanctuary anymore 
- Internal cleanup 
- Slight UI improvements
"""
