[plugin]
repository = "https://github.com/shdwp/xivFaderPlugin.git"
commit = "f6628249c3910c109c5f4b21ce242b7de1962bee"
owners = ["shdwp", "Aelexe", "Infiziert90"]
project_path = "FaderPlugin"
changelog = "Release v2.3.3.0\n- add WeaponUnsheathed state \n- Internal cleanup \n- slight UI improvements"
