[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "1489c6fb07178eaaecf2b2df280ac42bb9e0838b"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
+ Tracks current builds  
+ Builder to improve your builds  
+ Support for multiple FCs  
"""
