[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "2d80ffecbf4aba193f3efc1a92d3decef28aa6c9"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
- Added loot tracking
- WIP loot overview
- Fix imgui textcalc crash on startup
"""
