[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "63da289c84f7f18aa4400d39768a4ebbeaae7859"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[New]
+ Added customizable loot window (/sloot)
> Add items in the custom tab in the configuration
+ Added voyage log in the same window

[Builder]
+ Added optimized route
+ Added exp/min

[Tracker]
+ Added option to use character name 
+ Added option to use DateTime instead of ticking timer
"""
