[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "702312d7bc950b727f7f96d5db218628c73d5e62"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
- Finished FC Loot Overview
- Added return date/time

Planned features:
+ EXP optimizer
+ Unlockable routes
+ Save/Load builds and routes
+ Durability for each sub 
+ Durability calculation
+ Automatic build solver

If you have ideas or requests for additional features, please contact me through either the discord thread or Github issue page
You can find both of these in the about tab
"""
