[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "240a44bfe651b725bf59254b832c2f0e2c7f5733"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
[Tracker]
+ Added option to show both time and return date

[Config]
+ Added some styling to the config interface

[Fixes]
+ Fix impossible map setup after build change
+ Fix deadlock that could happen in EXP solver
"""
