[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "970aa619f68fad279dd420dee9305c03de60c79f"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
nofranz
"""
