[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "5dca0d85875a17b150062b339d2284230caf2fa6"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
- Fix bug that produced wrong tag and world names
"""
