[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "69f891c1739e5baecf72ca4eb7572449875067f6"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
+ Fix impossible map setup after build change
"""
