[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "31a65802356f110d15bb4f1b60ce912031185d91"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
+ Tracks current builds  
+ Builder to improve your builds  
+ Breakpoint calculation based on spreadsheet data
+ Support for multiple FCs  
"""
