[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "dc9896b66a371d5cd732f6aadb03f8dbbef9647e"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
- Added repair costs to details and builder 
"""
