[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "90014dc684609d11fefa9a0701fb207ee843a39b"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
- Added repair costs to details and builder 
- Added duration to builder 
"""
