[plugin]
repository = "https://github.com/Infiziert90/SubmarineTracker.git"
commit = "cb9e508306509dcb7ab3274fa79801b8a9d9a6b2"
owners = [
    "Infiziert90",
]
project_path = "SubmarineTracker"
changelog = """
- Add Timer and Routes to tracker
- Add config options to disable both of them
- Add About Tab
"""
