[plugin]
repository = "https://github.com/Infiziert90/WaymarkPresetPlugin.git"
commit = "02c3f6ac2182f9eced557f4bf7c4e305d4fb8fc7"
owners = [
    "PunishedPineapple",
    "abashby",
    "Infiziert90",
]
project_path = "WaymarkPresetPlugin"
changelog = '''
nofranz
'''
